[package]
name = "lru_cache"
version = "0.1.0"
edition = "2021"
authors = ["Votre Nom <votre@email.com>"]
description = "Une implémentation de cache LRU en Rust"

[dependencies]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "cache_benchmark"
harness = false